app/post/forms.py
#form file for the posts
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField, SelectField, RadioField
from wtforms.validators import ValidationError, DataRequired, Length
from app.models import User

class PostForm(FlaskForm):
	title = StringField('Title', validators=[DataRequired(), Length(min=1, max=20)])
	body = TextAreaField('Content:',validators=[DataRequired(), Length(min=1, max=1000)], render_kw={'class': 'form-control', 'rows': 40})
	visibility = RadioField('Visibility to others', choices=[('Private', 'Only visible to me'), ('Public', 'Visible to others')], validators=[DataRequired()])
	submit = SubmitField('Post')

app/post/__init__.py
from flask import Blueprint

bp = Blueprint('post', __name__)

from app.post import routes

app/post/routes.py
#Routes for the Posts
from flask import render_template, redirect, url_for, flash, request
from flask_login import login_user, current_user, logout_user, login_required
from flask_wtf.csrf import CsrfProtect
from flask_babel import _, get_locale
from werkzeug.urls import url_parse

from app import db
from app.post import bp
from app.models import User, Post
from app.post.forms import PostForm

@bp.route('/view/<post_mapping>')
def post_mapping(post_mapping):
	post = Post.query.filter_by(url_mapping=post_mapping).first_or_404()
	user = User.query.filter_by(id=post.user_id).first()
	return render_template('post/view_post.html', post=post, username=user)

@bp.route('/export_posts')
@login_required
def export_posts():
	if current_user.get_task_in_progress('export_posts'):
		flash('An export task is currently in progress')
	else:
		current_user.launch_task('export_posts', 'Exporting posts...')
		db.session.commit()
	return redirect(url_for('main.user', username=current_user.username))

@bp.route('/newpost', methods=['GET','POST'])
@login_required
def newpost():
		form = PostForm()
		if form.validate_on_submit():
			post = Post(title=form.title.data,body=form.body.data, author=current_user, visibility=form.visibility.data)
			post.add_mapping()
			db.session.add(post)
			db.session.commit()
			flash('Your post is now live!')
			return redirect(url_for('main.feed'))
		return	render_template('post/newpost.html', form=form)

app/templates/_post.html
<a href="{{ url_for('post.post_mapping', post_mapping=post.url_mapping ) }}">
<table class="table table-hover">
	<tr>
		<td width="70px">
			<a href="{{ url_for('main.user', username=post.author.username) }}">
				<img src="{{ post.author.avatar(70) }}"></td>
			</a>
		<td>
			{% set user_link %}
				<span class="user_popup">
					<a href="{{ url_for('main.user', username=post.author.username) }}">
						{{ post.author.username }}
					</a>
				</span>
			{% endset %}
				{{ user_link }} said {{ moment(post.timestamp).fromNow() }}
			<br>
				{{ post.title }}
		</td>
	</tr>
</table>
</a>

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
{% if title %}{{ title }} - Microblog{% else %} Welcome to Microblog {% endif %}
{% endblock %}

{% block navbar %}
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('main.home') }}">Microblog</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{{ url_for('main.feed') }}">Feed</a></li>
        {%if current_user.is_authenticated %}
          <li><a href="{{ url_for('post.newpost') }}">Create Post</a></li>
          {% if current_user.is_admin() %}
          <li><a href="{{ url_for('admin.userList')}}">Users</a></li>
          {% endif %}
        {% endif %}
      </ul>
      {% if g.search_form %}
      <form class="navbar-form navbar-left" method="get" action="{{ url_for('main.search') }}">
        <div class="form-group">
          {{ g.search_form.q(size=20, class='form-control', placeholder=g.search_form.q.label.text) }}
        </div>
      </form>
      {% endif %}
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_anonymous %}
        <li><a href="{{ url_for('auth.login') }}">Login</a></li>
        {% else %}
        <li>
          <a href="{{ url_for('main.messages') }}">
            Messages
            {% set new_messages = current_user.new_messages() %}
            {% if new_messages %}
            <span id="message_count" class="badge" style="visibility:
										{% if new_messages %}
											visible
										{% else %}
											hidden
										{% endif %}
									;">
              {{ new_messages }}
            </span>
            {% endif %}
          </a>
        </li>
        <li><a href="{{ url_for('main.user', username=current_user.username) }}">Profile</a></li>

        <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
{% endblock %}

{% block content %}
<div class="container">
  {% with messages = get_flashed_messages() %}
  {% if messages %}
  {% for message in messages %}
  <div class="alert alert-info" role="alert">{{ message }}</div>
  {% endfor %}
  {% endif %}
  {% endwith %}

  {% block app_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{{ moment.lang(g.locale) }}
<script>
  $(function() {
    var timer = null;
    var xhr = null;
    $('.user_popup').hover(
      function(event) {
        // mouse in event handler
        var elem = $(event.currentTarget);
        timer = setTimeout(function() {
          timer = null;
          xhr = $.ajax(
            '/user/' + elem.first().text().trim() + '/popup').done(
            function(data) {
              xhr = null;
              elem.popover({
                trigger: 'manual',
                html: true,
                animation: false,
                container: elem,
                content: data
              }).popover('show');
              flask_moment_render_all();
            }
          );
        }, 1000);
      },
      function(event) {
        // mouse out event handler
        var elem = $(event.currentTarget);
        if (timer) {
          clearTimeout(timer);
          timer = null;
        } else if (xhr) {
          xhr.abort();
          xhr = null;
        } else {
          elem.popover('destroy');
        }
      }
    );
  });

  function set_message_count(n) {
    $('#message_count').text(n);
    $('#message_count').css('visibility', n ? 'visible' : 'hidden');
  }

  {% if current_user.is_authenticated %}
  $(function() {
    var since = 0;
    setInterval(function() {
      $.ajax('{{ url_for('main.notifications') }}?since=' + since).done(
        function(notifications) {
          for (var i = 0; i < notifications.length; i++) {
            if (notifications[i].name == 'unread_message_count')
              set_message_count(notifications[i].data);
            since = notifications[i].timestamp;
          }
        }
      );
    }, 10000);
  }); {
    {% endif %}
  }
</script>
{% endblock %}

app/templates/edit_profile.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
	<h1>Edit Profile</h1>
	<div class="row">
		<div class="col-md-4">
			{{ wtf.quick_form(form) }}
		</div>
	</div>
{% endblock %}

app/templates/feed.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Hi, {{ current_user.username }}!</h1>
    {% if form %}
    {{ wtf.quick_form(form) }}
    <br>
    {% endif %}
    {% if is_following(username) %}
        {% for post in posts %}
            {% include '_post.html' %}
        {% endfor %}
    {% endif %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> Newer posts
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    Older posts <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
	{% if current_user.is_authenticated %}
		<h1>Hi, {{ current_user.username }}!</h1>
	{% else %}
		<h1>Hi, guest!</h1>
	{% endif %}
	{% if form %}
		{{ wtf.quick_form(form) }}
		<br>
	{% endif %}
	{% for post in posts %}
		{% include '_post.html' %}
	{% endfor %}
	<nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span>
					Newer posts
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    Older posts
					<span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/templates/messages.html
{% extends "base.html" %}

{% block app_content %}
	<h1> Messages </h1>
	{% for post in messages %}
		{% include '_post.html' %}
	{% endfor %}
	<nav aria-label="...">
		<ul class="pager">
			<li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> 
					Newer messages
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    Older messages' 
					<span aria-hidden="true">&rarr;</span>
                </a>
            </li>
		</ul>
	</nav>
{% endblock %} 

app/templates/search.html
{% extends "base.html" %}

{% block app_content %}
	<h1>{{ 'Search Results' }}</h1>
	{% for post in posts %}
		{% include '_post.html' %}
	{% endfor %}
	<nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span>
                    Previous results
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    Next results
                    <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/templates/send_message.html


<head>

<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<style>
body{padding-top:0px;}
#larger {
font-size: 40px;
}
</style>
</head>

<script>
/**
 *
 * jquery.charcounter.js version 1.2
 * requires jQuery version 1.2 or higher
 * Copyright (c) 2007 Tom Deater (http://www.tomdeater.com)
 * Licensed under the MIT License:
 * http://www.opensource.org/licenses/mit-license.php
 * 
 */
 
(function($) {
    /**
	 * attaches a character counter to each textarea element in the jQuery object
	 * usage: $("#myTextArea").charCounter(max, settings);
	 */
	
	$.fn.charCounter = function (max, settings) {
		max = max || 100;
		settings = $.extend({
			container: "<span></span>",
			classname: "charcounter",
			format: "(%1 characters remaining)",
			pulse: true,
			delay: 0
		}, settings);
		var p, timeout;
		
		function count(el, container) {
			el = $(el);
			if (el.val().length > max) {
			    el.val(el.val().substring(0, max));
			    if (settings.pulse && !p) {
			    	pulse(container, true);
			    };
			};
			if (settings.delay > 0) {
				if (timeout) {
					window.clearTimeout(timeout);
				}
				timeout = window.setTimeout(function () {
					container.html(settings.format.replace(/%1/, (max - el.val().length)));
				}, settings.delay);
			} else {
				container.html(settings.format.replace(/%1/, (max - el.val().length)));
			}
		};
		
		function pulse(el, again) {
			if (p) {
				window.clearTimeout(p);
				p = null;
			};
			el.animate({ opacity: 0.1 }, 100, function () {
				$(this).animate({ opacity: 1.0 }, 100);
			});
			if (again) {
				p = window.setTimeout(function () { pulse(el) }, 200);
			};
		};
		
		return this.each(function () {
			var container;
			if (!settings.container.match(/^<.+>$/)) {
				// use existing element to hold counter message
				container = $(settings.container);
			} else {
				// append element to hold counter message (clean up old element first)
				$(this).next("." + settings.classname).remove();
				container = $(settings.container)
								.insertAfter(this)
								.addClass(settings.classname);
			}
			$(this)
				.unbind(".charCounter")
				.bind("keydown.charCounter", function () { count(this, container); })
				.bind("keypress.charCounter", function () { count(this, container); })
				.bind("keyup.charCounter", function () { count(this, container); })
				.bind("focus.charCounter", function () { count(this, container); })
				.bind("mouseover.charCounter", function () { count(this, container); })
				.bind("mouseout.charCounter", function () { count(this, container); })
				.bind("paste.charCounter", function () { 
					var me = this;
					setTimeout(function () { count(me, container); }, 10);
				});
			if (this.addEventListener) {
				this.addEventListener('input', function () { count(this, container); }, false);
			};
			count(this, container);
		});
	};

})(jQuery);


</script>
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
	<h1> Send Message to {{ recipient }} </h1>
<div class="container">   
                    
                        <div class="col-md-4">
				{{ wtf.quick_form(form, id='larger') }}
			</div>
</div>
{% endblock %}

app/templates/user.html
{% extends "base.html" %}

{% block app_content %}




	<table>
		<tr>
			<td width="256px"><img src="{{ user.avatar(256) }}"></td>
			<td>
			<div class=container>
				<h1>User: {{ user.username }} </h1>
				{% if user.about_me %}
					<p> {{ user.about_me }} </p>
				{% endif %}
				{% if user.last_seen %}
					<p>Last seen on: {{ moment(user.last_seen).format('LLL') }}
				{% endif %}
				<p>
					{{ user.followers.count() }} followers,
					{{ user.followed.count() }} following
				</p>
				{% if user == current_user %} <br>
					<p>
						<a href="{{ url_for('main.edit_profile') }}">
							Edit your Profile
						</a>
					</p>
					<p>
						<a href="{{ url_for('post.export_posts') }}">
							Export your posts
						</a>
					</p>
				{% elif not current_user.is_following(user) %}
					<p><a href="{{ url_for('main.follow', username=user.username) }}">Follow</a></p>
				{% else %}
					<p><a href="{{ url_for('main.unfollow', username=user.username) }}">UnFollow</a></p>
				{% endif %}
				{% if user != current_user %}
					<p>
						<a href="{{ url_for('main.send_message', recipient=user.username) }}">
							Send private message
						</a>
					</p>
				{% endif %}
			</div>
			</td>
	</table>
	{% for post in posts %}
        {% include '_post.html' %}
    {% endfor %}
	<hr>
	<nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span>
					Newer posts
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    Older posts
					<span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/templates/user_popup.html
<table class="table">
	<tr>
		<td width="64" style="border: 0px;"><img src="{{ user.avatar(64) }}"></td>
		<td style="border: 0px;">
			<p>
			<a href="{{ url_for('main.user', username=user.username) }}">
				{{ user.username }}
			</a>
			<p>
			<small>
				{% if user.about_me %}<p>{{ user.about_me }}</p> {% endif %}
				{% if user.last_seen %}
				<p> Last seen on {{ moment(user.last_seen).format('111') }}</p>
				{% endif %}
				<p> 
					{{ user.followers.count() }} followers,
					{{ user.followed.count() }} following
				</p>
				{% if user != user.current_user %}
					{% if not current_user.is_following(user) %}
						<a href="{{ url_for('main.follow', username=user.username) }}">
							Follow
						</a>
					{% else %}
						<a href="{{ url_for('main.unfollow', username=user.username) }}"
							Unfollow
						</a>
					{% endif %}
				{% endif %}
			</small>
		</td>
	</tr>
</table>